// Every tunable number the engine uses. All are user-editable; Evidence-tagged values show a
// warning when set outside `evidenceRange`. Stored values are merged over these defaults on read,
// so adding a key never needs a migration.

export type SettingTag = 'Evidence' | 'Heuristic'

export type SettingGroup =
  | 'energy'
  | 'rateBands'
  | 'macros'
  | 'checkin'
  | 'body'
  | 'phases'
  | 'volume'
  | 'progression'
  | 'deload'
  | 'app'

export interface SettingMeta {
  readonly key: string
  readonly label: string
  readonly group: SettingGroup
  readonly tag: SettingTag
  readonly unit: string
  readonly default: number
  readonly min: number
  readonly max: number
  readonly step: number
  /** Range backed by the cited evidence; only for Evidence-tagged settings. */
  readonly evidenceRange?: readonly [number, number]
  readonly help: string
}

export const SETTINGS_REGISTRY = [
  // ── Energy / maintenance ────────────────────────────────────────────────
  {
    key: 'activityFactor',
    label: 'Activity factor',
    group: 'energy',
    tag: 'Heuristic',
    unit: '×',
    default: 1.55,
    min: 1.2,
    max: 2.2,
    step: 0.05,
    help: 'Multiplies the average of Katch-McArdle and Mifflin-St Jeor RMR to estimate maintenance.',
  },
  {
    key: 'trendAlpha',
    label: 'Trend smoothing α',
    group: 'energy',
    tag: 'Heuristic',
    unit: '',
    default: 0.1,
    min: 0.02,
    max: 0.5,
    step: 0.01,
    help: 'Exponential moving average weight for trend weight (Hacker’s Diet uses 0.1).',
  },
  {
    key: 'kcalPerLb',
    label: 'Energy per lb of trend change',
    group: 'energy',
    tag: 'Heuristic',
    unit: 'kcal/lb',
    default: 3500,
    min: 2500,
    max: 4500,
    step: 50,
    help: 'Used for measured maintenance and to turn a weekly rate into a daily kcal offset.',
  },
  {
    key: 'tdeeWindowMinDays',
    label: 'Maintenance window (min)',
    group: 'energy',
    tag: 'Heuristic',
    unit: 'days',
    default: 14,
    min: 7,
    max: 28,
    step: 1,
    help: 'Shortest intake/trend window used to measure maintenance.',
  },
  {
    key: 'tdeeWindowMaxDays',
    label: 'Maintenance window (max)',
    group: 'energy',
    tag: 'Heuristic',
    unit: 'days',
    default: 21,
    min: 7,
    max: 42,
    step: 1,
    help: 'Longest window; the longest qualifying window in [min, max] is used.',
  },
  {
    key: 'tdeeMinLoggedPct',
    label: 'Minimum days logged',
    group: 'energy',
    tag: 'Heuristic',
    unit: '%',
    default: 80,
    min: 50,
    max: 100,
    step: 5,
    help: 'Share of days in the window that need both intake and a weigh-in.',
  },
  {
    key: 'tdeeMaxWeeklyChangeKcal',
    label: 'Max weekly maintenance-estimate change',
    group: 'energy',
    tag: 'Heuristic',
    unit: 'kcal',
    default: 150,
    min: 50,
    max: 500,
    step: 25,
    help: 'Caps week-over-week changes in the measured maintenance estimate. The first measured estimate replaces the formula uncapped.',
  },
  {
    key: 'tdeeExcludeDaysAfterStart',
    label: 'Days excluded after a phase start',
    group: 'energy',
    tag: 'Heuristic',
    unit: 'days',
    default: 7,
    min: 0,
    max: 14,
    step: 1,
    help: 'Water and glycogen shifts after a phase change bias measured maintenance.',
  },

  // ── Rate bands (% bodyweight per week) ──────────────────────────────────
  {
    key: 'bulkRateMinPct',
    label: 'Bulk rate: minimum',
    group: 'rateBands',
    tag: 'Evidence',
    unit: '%BW/wk',
    default: 0.25,
    min: 0,
    max: 1.5,
    step: 0.05,
    evidenceRange: [0.25, 0.5],
    help: 'Iraki 2019: +0.25–0.5% bodyweight/week for novices and intermediates.',
  },
  {
    key: 'bulkRateMaxPct',
    label: 'Bulk rate: maximum',
    group: 'rateBands',
    tag: 'Evidence',
    unit: '%BW/wk',
    default: 0.5,
    min: 0,
    max: 1.5,
    step: 0.05,
    evidenceRange: [0.25, 0.5],
    help: 'Iraki 2019: +0.25–0.5% bodyweight/week for novices and intermediates.',
  },
  {
    key: 'cutRateMinPct',
    label: 'Cut rate: fastest',
    group: 'rateBands',
    tag: 'Evidence',
    unit: '%BW/wk',
    default: -0.75,
    min: -1.5,
    max: 0,
    step: 0.05,
    evidenceRange: [-1, -0.5],
    help: 'Helms 2014: lose 0.5–1% bodyweight/week; leaner lifters stay near the low end. Stored as the numerically smaller value.',
  },
  {
    key: 'cutRateMaxPct',
    label: 'Cut rate: slowest',
    group: 'rateBands',
    tag: 'Evidence',
    unit: '%BW/wk',
    default: -0.5,
    min: -1.5,
    max: 0,
    step: 0.05,
    evidenceRange: [-1, -0.5],
    help: 'Helms 2014: lose 0.5–1% bodyweight/week.',
  },
  {
    key: 'maintRateMinPct',
    label: 'Maintenance band: low',
    group: 'rateBands',
    tag: 'Heuristic',
    unit: '%BW/wk',
    default: -0.25,
    min: -1,
    max: 0,
    step: 0.05,
    help: 'Trend rate below this counts as losing.',
  },
  {
    key: 'maintRateMaxPct',
    label: 'Maintenance band: high',
    group: 'rateBands',
    tag: 'Heuristic',
    unit: '%BW/wk',
    default: 0.25,
    min: 0,
    max: 1,
    step: 0.05,
    help: 'Trend rate above this counts as gaining.',
  },

  // ── Macros and rounding ─────────────────────────────────────────────────
  {
    key: 'bulkProteinGPerKgBw',
    label: 'Bulk protein',
    group: 'macros',
    tag: 'Evidence',
    unit: 'g/kg BW',
    default: 2.0,
    min: 1.2,
    max: 3.5,
    step: 0.1,
    evidenceRange: [1.6, 2.2],
    help: 'Morton 2018: gains plateau near 1.6 g/kg, upper bound near 2.2.',
  },
  {
    key: 'maintProteinGPerKgBw',
    label: 'Maintenance protein',
    group: 'macros',
    tag: 'Heuristic',
    unit: 'g/kg BW',
    default: 2.0,
    min: 1.2,
    max: 3.5,
    step: 0.1,
    help: 'Not in the spec’s defaults; matches its 150 g maintenance target.',
  },
  {
    key: 'cutProteinGPerKgLbm',
    label: 'Cut protein',
    group: 'macros',
    tag: 'Evidence',
    unit: 'g/kg lean',
    default: 2.7,
    min: 1.6,
    max: 4,
    step: 0.1,
    evidenceRange: [2.3, 3.1],
    help: 'Helms 2014: 2.3–3.1 g per kg of lean mass on a cut.',
  },
  {
    key: 'cutProteinFallbackGPerKgBw',
    label: 'Cut protein without body fat',
    group: 'macros',
    tag: 'Heuristic',
    unit: 'g/kg BW',
    default: 2.2,
    min: 1.6,
    max: 3.5,
    step: 0.1,
    help: 'Used when no body-fat reading exists to estimate lean mass.',
  },
  {
    key: 'fatPct',
    label: 'Fat share of calories',
    group: 'macros',
    tag: 'Evidence',
    unit: '%',
    default: 25,
    min: 10,
    max: 45,
    step: 1,
    evidenceRange: [15, 30],
    help: '20–30% on a bulk and 15–30% on a cut; carbs fill the rest.',
  },
  {
    key: 'kcalRoundTo',
    label: 'Round calorie targets to',
    group: 'macros',
    tag: 'Heuristic',
    unit: 'kcal',
    default: 50,
    min: 1,
    max: 100,
    step: 1,
    help: 'Targets are rounded when saved; maintenance is kept unrounded.',
  },
  {
    key: 'proteinRoundTo',
    label: 'Round protein targets to',
    group: 'macros',
    tag: 'Heuristic',
    unit: 'g',
    default: 5,
    min: 1,
    max: 10,
    step: 1,
    help: 'Protein target rounding.',
  },
  {
    key: 'surplusWarnPct',
    label: 'Warn above surplus',
    group: 'macros',
    tag: 'Heuristic',
    unit: '%',
    default: 15,
    min: 5,
    max: 30,
    step: 1,
    help: 'Phase setup warns when the implied surplus exceeds this share of maintenance.',
  },

  // ── Weekly check-in ─────────────────────────────────────────────────────
  {
    key: 'checkinStepKcal',
    label: 'Bulk/cut adjustment',
    group: 'checkin',
    tag: 'Heuristic',
    unit: 'kcal',
    default: 150,
    min: 50,
    max: 300,
    step: 25,
    help: 'Calorie change suggested when the trend misses its band (spec: 100–150).',
  },
  {
    key: 'checkinMaintStepKcal',
    label: 'Maintenance adjustment',
    group: 'checkin',
    tag: 'Heuristic',
    unit: 'kcal',
    default: 100,
    min: 50,
    max: 300,
    step: 25,
    help: 'Change back toward zero when maintenance drifts outside its band.',
  },
  {
    key: 'checkinMissesRequired',
    label: 'Weeks outside band before a change',
    group: 'checkin',
    tag: 'Heuristic',
    unit: 'weeks',
    default: 2,
    min: 1,
    max: 4,
    step: 1,
    help: 'Consecutive same-direction misses needed before suggesting a change.',
  },
  {
    key: 'checkinNoChangeWeeks',
    label: 'No-change weeks at phase start',
    group: 'checkin',
    tag: 'Heuristic',
    unit: 'weeks',
    default: 1,
    min: 0,
    max: 3,
    step: 1,
    help: 'Water and glycogen shifts: no calorie change (and no counted miss) in these first weeks.',
  },
  {
    key: 'cutStepsAlternative',
    label: 'Cut: extra steps instead of calories',
    group: 'checkin',
    tag: 'Heuristic',
    unit: 'steps/day',
    default: 2000,
    min: 500,
    max: 5000,
    step: 250,
    help: 'Offered on a cut that is losing too slowly.',
  },

  // ── Body data ───────────────────────────────────────────────────────────
  {
    key: 'weighInConfirmDeviationPct',
    label: 'Confirm weigh-ins that differ by',
    group: 'body',
    tag: 'Heuristic',
    unit: '%',
    default: 3,
    min: 1,
    max: 10,
    step: 0.5,
    help: 'Ask before saving a weigh-in this far from the trend (typo guard).',
  },
  {
    key: 'sevenDayAvgMinReadings',
    label: '7-day average: minimum readings',
    group: 'body',
    tag: 'Heuristic',
    unit: 'readings',
    default: 3,
    min: 1,
    max: 7,
    step: 1,
    help: 'The 7-day average is shown only with at least this many weigh-ins.',
  },
  {
    key: 'bfSmoothN',
    label: 'Body fat: readings averaged',
    group: 'body',
    tag: 'Heuristic',
    unit: 'readings',
    default: 3,
    min: 1,
    max: 8,
    step: 1,
    help: 'Smoothed body fat = mean of the last N readings within the window.',
  },
  {
    key: 'bfSmoothWindowDays',
    label: 'Body fat: window',
    group: 'body',
    tag: 'Heuristic',
    unit: 'days',
    default: 28,
    min: 7,
    max: 90,
    step: 1,
    help: 'Only readings this recent are averaged.',
  },
  {
    key: 'bfSmoothMin',
    label: 'Body fat: minimum readings',
    group: 'body',
    tag: 'Heuristic',
    unit: 'readings',
    default: 2,
    min: 1,
    max: 8,
    step: 1,
    help: 'Fewer readings than this falls back to the latest single reading.',
  },
  {
    key: 'bfSingleFallbackDays',
    label: 'Body fat: single-reading fallback age',
    group: 'body',
    tag: 'Heuristic',
    unit: 'days',
    default: 90,
    min: 7,
    max: 365,
    step: 1,
    help: 'A lone reading older than this is ignored.',
  },

  // ── Phases ──────────────────────────────────────────────────────────────
  {
    key: 'bulkBfCeilingPct',
    label: 'Bulk body-fat ceiling',
    group: 'phases',
    tag: 'Heuristic',
    unit: '%',
    default: 18,
    min: 8,
    max: 30,
    step: 0.5,
    help: 'Prompt to end the bulk when smoothed body fat reaches this.',
  },
  {
    key: 'cutBfTargetPct',
    label: 'Cut body-fat target',
    group: 'phases',
    tag: 'Heuristic',
    unit: '%',
    default: 12,
    min: 5,
    max: 25,
    step: 0.5,
    help: 'Prompt to end the cut when smoothed body fat reaches this.',
  },
  {
    key: 'bulkPlannedWeeks',
    label: 'Bulk: planned length',
    group: 'phases',
    tag: 'Heuristic',
    unit: 'weeks',
    default: 20,
    min: 4,
    max: 52,
    step: 1,
    help: 'Soft note at this length.',
  },
  {
    key: 'bulkMaxWeeks',
    label: 'Bulk: maximum length',
    group: 'phases',
    tag: 'Heuristic',
    unit: 'weeks',
    default: 26,
    min: 4,
    max: 52,
    step: 1,
    help: 'Firm prompt to end the bulk.',
  },
  {
    key: 'cutPlannedWeeks',
    label: 'Cut: planned length',
    group: 'phases',
    tag: 'Heuristic',
    unit: 'weeks',
    default: 14,
    min: 2,
    max: 30,
    step: 1,
    help: 'Soft note at this length.',
  },
  {
    key: 'cutMaxWeeks',
    label: 'Cut: maximum length',
    group: 'phases',
    tag: 'Heuristic',
    unit: 'weeks',
    default: 16,
    min: 2,
    max: 30,
    step: 1,
    help: 'Firm prompt to end the cut.',
  },
  {
    key: 'maintWeeks',
    label: 'Maintenance length',
    group: 'phases',
    tag: 'Heuristic',
    unit: 'weeks',
    default: 4,
    min: 1,
    max: 12,
    step: 1,
    help: 'Prompt to start the next phase (spec: 2–4 weeks).',
  },
  {
    key: 'cutStrengthDropPct',
    label: 'Cut: main-lift strength drop',
    group: 'phases',
    tag: 'Heuristic',
    unit: '%',
    default: 5,
    min: 1,
    max: 20,
    step: 0.5,
    help: 'Prompt to end the cut if main-lift e1RMs fall more than this.',
  },
  {
    key: 'strengthLookbackDays',
    label: 'Strength drop lookback',
    group: 'phases',
    tag: 'Heuristic',
    unit: 'days',
    default: 21,
    min: 7,
    max: 56,
    step: 1,
    help: 'Compare recent best e1RMs with this many days earlier.',
  },
  {
    key: 'strengthWindowDays',
    label: 'Strength comparison window',
    group: 'phases',
    tag: 'Heuristic',
    unit: 'days',
    default: 7,
    min: 3,
    max: 21,
    step: 1,
    help: 'Best e1RM within this window at each end of the lookback.',
  },

  // ── Volume ──────────────────────────────────────────────────────────────
  {
    key: 'weeklyVolumeMin',
    label: 'Weekly sets: low below',
    group: 'volume',
    tag: 'Evidence',
    unit: 'sets',
    default: 10,
    min: 0,
    max: 30,
    step: 1,
    evidenceRange: [10, 20],
    help: 'Trained lifters do well on ~10–20 fractional sets per muscle per week.',
  },
  {
    key: 'weeklyVolumeMax',
    label: 'Weekly sets: high above',
    group: 'volume',
    tag: 'Evidence',
    unit: 'sets',
    default: 20,
    min: 5,
    max: 40,
    step: 1,
    evidenceRange: [10, 20],
    help: 'Trained lifters do well on ~10–20 fractional sets per muscle per week.',
  },
  {
    key: 'sessionCap',
    label: 'Per-session cap',
    group: 'volume',
    tag: 'Evidence',
    unit: 'sets',
    default: 11,
    min: 4,
    max: 30,
    step: 0.5,
    evidenceRange: [10, 12],
    help: 'No detectable extra growth past ~11 fractional sets per muscle per session (Remmert 2025, preprint).',
  },
  {
    key: 'rampEveryWeeks',
    label: 'Bulk: add a set to a lagging muscle every',
    group: 'volume',
    tag: 'Heuristic',
    unit: 'weeks',
    default: 3,
    min: 1,
    max: 8,
    step: 1,
    help: 'Suggests +1 set for muscles you mark as lagging (spec: every 3–4 weeks).',
  },
  {
    key: 'trainingWeekStartDay',
    label: 'Training week starts on',
    group: 'volume',
    tag: 'Heuristic',
    unit: 'weekday',
    default: 1,
    min: 0,
    max: 6,
    step: 1,
    help: '0 = Sunday, 1 = Monday. Used for weekly logged volume.',
  },

  // ── Progression ─────────────────────────────────────────────────────────
  {
    key: 'missesBeforeDrop',
    label: 'Sessions below range before a drop',
    group: 'progression',
    tag: 'Heuristic',
    unit: 'sessions',
    default: 2,
    min: 1,
    max: 5,
    step: 1,
    help: 'Consecutive sessions with a set below the rep range before reducing load.',
  },
  {
    key: 'dropPct',
    label: 'Load drop',
    group: 'progression',
    tag: 'Heuristic',
    unit: '%',
    default: 10,
    min: 5,
    max: 20,
    step: 0.5,
    help: 'Drop = max(1, floor(pct × load ÷ step)) whole steps (spec: 5–10%).',
  },
  {
    key: 'e1rmRepCutoff',
    label: 'e1RM rep cutoff',
    group: 'progression',
    tag: 'Heuristic',
    unit: 'reps',
    default: 12,
    min: 6,
    max: 20,
    step: 1,
    help: 'Exercises whose rep range tops out above this track reps-at-load instead of e1RM.',
  },
  {
    key: 'stallWindow',
    label: 'Stall window',
    group: 'progression',
    tag: 'Heuristic',
    unit: 'sessions',
    default: 3,
    min: 2,
    max: 8,
    step: 1,
    help: 'No improvement over this many sessions flags a stall.',
  },
  {
    key: 'stallRemedyWeeks',
    label: 'Stall remedy length',
    group: 'progression',
    tag: 'Heuristic',
    unit: 'weeks',
    default: 2,
    min: 1,
    max: 6,
    step: 1,
    help: 'How long to try a variation or one fewer set.',
  },
  {
    key: 'restExtendSec',
    label: 'Rest timer extend',
    group: 'progression',
    tag: 'Heuristic',
    unit: 's',
    default: 30,
    min: 10,
    max: 120,
    step: 5,
    help: 'The +N s button on the rest timer.',
  },

  // ── Deload ──────────────────────────────────────────────────────────────
  {
    key: 'deloadStallCount',
    label: 'Stalled exercises that suggest a deload',
    group: 'deload',
    tag: 'Heuristic',
    unit: 'exercises',
    default: 3,
    min: 1,
    max: 10,
    step: 1,
    help: '“Several lifts stall at once.”',
  },
  {
    key: 'deloadJointPainHits',
    label: 'Joint-pain flags that suggest a deload',
    group: 'deload',
    tag: 'Heuristic',
    unit: 'sessions',
    default: 2,
    min: 1,
    max: 5,
    step: 1,
    help: 'Flags needed within the window below.',
  },
  {
    key: 'deloadJointPainWindow',
    label: 'Joint-pain window',
    group: 'deload',
    tag: 'Heuristic',
    unit: 'sessions',
    default: 3,
    min: 1,
    max: 10,
    step: 1,
    help: 'Recent sessions checked for joint-pain flags.',
  },
  {
    key: 'deloadSetFraction',
    label: 'Deload set fraction',
    group: 'deload',
    tag: 'Heuristic',
    unit: '×',
    default: 0.5,
    min: 0.25,
    max: 1,
    step: 0.05,
    help: 'Deload sets = ceil(sets × fraction).',
  },
  {
    key: 'deloadLoadCutPct',
    label: 'Deload load cut',
    group: 'deload',
    tag: 'Heuristic',
    unit: '%',
    default: 10,
    min: 0,
    max: 30,
    step: 0.5,
    help: 'Applied with the same whole-step routine as a drop.',
  },
  {
    key: 'deloadSessions',
    label: 'Deload length',
    group: 'deload',
    tag: 'Heuristic',
    unit: 'sessions',
    default: 5,
    min: 1,
    max: 14,
    step: 1,
    help: 'One program cycle by default.',
  },

  // ── App ─────────────────────────────────────────────────────────────────
  {
    key: 'backupReminderDays',
    label: 'Backup reminder',
    group: 'app',
    tag: 'Heuristic',
    unit: 'days',
    default: 7,
    min: 1,
    max: 60,
    step: 1,
    help: 'Remind to export a backup after this many days.',
  },
] as const satisfies readonly SettingMeta[]

export type SettingKey = (typeof SETTINGS_REGISTRY)[number]['key']
export type Settings = Readonly<Record<SettingKey, number>>

const META_BY_KEY = new Map<string, SettingMeta>(SETTINGS_REGISTRY.map((m) => [m.key, m]))

export const DEFAULT_SETTINGS: Settings = Object.freeze(
  Object.fromEntries(SETTINGS_REGISTRY.map((m) => [m.key, m.default])) as Record<
    SettingKey,
    number
  >,
)

export function settingMeta(key: SettingKey): SettingMeta {
  const m = META_BY_KEY.get(key)
  if (!m) throw new RangeError(`Unknown setting: ${key}`)
  return m
}

export function isSettingKey(key: string): key is SettingKey {
  return META_BY_KEY.has(key)
}

/**
 * Merge stored overrides over the defaults. Unknown keys and non-finite values are ignored;
 * values are clamped to [min, max].
 */
export function resolveSettings(
  stored: Readonly<Record<string, unknown>> | null | undefined,
): Settings {
  const out: Record<string, number> = { ...DEFAULT_SETTINGS }
  if (stored) {
    for (const [k, v] of Object.entries(stored)) {
      const meta = META_BY_KEY.get(k)
      if (!meta || typeof v !== 'number' || !Number.isFinite(v)) continue
      out[k] = Math.min(meta.max, Math.max(meta.min, v))
    }
  }
  return Object.freeze(out) as Settings
}

/** True when an Evidence-tagged setting is set outside its evidence range. */
export function outOfEvidenceRange(key: SettingKey, value: number): boolean {
  const range = settingMeta(key).evidenceRange
  if (!range) return false
  return value < range[0] || value > range[1]
}
